config/routes.rb
Rails.application.routes.draw do


  get 'lots/show'
  get 'pages/home'
  get 'pages/csv'
  get 'pages/smarter'
  get 'search'   => 'search#index'
  get  'about'   => "pages#about"
  get  'faq'   => "pages#faq"
  get  'how_to_buy'   => "pages#how_to_buy"
  get  'why_mitsab'   => "pages#why_mitsab"
  get  'contact' => "pages#contact"
  post  'contact' => "pages#contact_email"
  get  'error' => "pages#error"

  
  devise_for :users

  resources :lots do
  	resources :bids
    resources :watchlists
  end

  resources :watchlists
  get "/my-bids" => "watchlists#bids"
  namespace :admin do
    get '', to: 'dashboard#index', as: '/' 
    get '/auction' => "dashboard#auction"
    resources :lots
    resources :users
    resources :reports
    resources :bulk_upload
    get 'csv/:id' => "bulk_upload#csv"
    get 'dashboard/upload' => "dashboard#upload_csv"
    get 'dashboard/resque' => "dashboard#resque"
    get 'bids/approve/:id' => "bids#approve"
    get 'bids/reject/:id' => "bids#reject"
    mount Resque::Server.new, :at => "/resque"
  end

  root "pages#home"
end

app/models/lot.rb
class Lot < ApplicationRecord

	scope :make, -> (make) { where make: make }
  scope :color, -> (color) { where color: color }
  scope :drive, -> (drive) { where drive: drive }
  scope :has_keys, -> (has_keys) { where has_keys: has_keys }
  scope :year, -> (year) { where year: year }
  scope :state, -> (state) { where state: state }
  scope :lot_number, -> (lot_number) { where lot_number: lot_number }
  scope :buy_now_price, -> (buy_now_price) { where("buy_now_price > 0")}
  scope :auction, -> (auction) { Lot.joins(:bids).group('lots.id').having("count(bids.id)>0")}

	self.primary_key = 'lot_number'
	validates :lot_number, uniqueness: true
  has_many :bids
	has_many :watchlists
  accepts_nested_attributes_for :bids
	accepts_nested_attributes_for :watchlists
end

app/controllers/admin/lots_controller.rb
class Admin::LotsController < Admin::AdminController
  before_action :authenticate_user!
  layout 'admin'
  before_action :set_admin_lot, only: [:show, :edit, :update, :destroy]

  # GET /admin/lots
  # GET /admin/lots.json
  def index
    #@admin_lots = Lot.paginate(:page => params[:page], :per_page => 8)
    @admin_lots = Lot.paginate(:page => params[:page], :per_page => 20)
    filtering_params(params).each do |key, value|
    @admin_lots = @admin_lots.public_send(key, value) if value.present?
    end
  end

  # GET /admin/lots/1
  # GET /admin/lots/1.json
  def show
  end

  # GET /admin/lots/new
  def new
    @admin_lot = Lot.new
  end

  # GET /admin/lots/1/edit
  def edit
  end

  # POST /admin/lots
  # POST /admin/lots.json
  def create
    @admin_lot = Lot.new(admin_lot_params)

    respond_to do |format|
      if @admin_lot.save
        format.html { redirect_to @admin_lot, notice: 'Lot was successfully created.' }
        format.json { render :show, status: :created, location: @admin_lot }
      else
        format.html { render :new }
        format.json { render json: @admin_lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/lots/1
  # PATCH/PUT /admin/lots/1.json
  def update
    respond_to do |format|
      if @admin_lot.update(admin_lot_params)
        format.html { redirect_to @admin_lot, notice: 'Lot was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_lot }
      else
        format.html { render :edit }
        format.json { render json: @admin_lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/lots/1
  # DELETE /admin/lots/1.json
  def destroy
    @admin_lot.destroy
    respond_to do |format|
      format.html { redirect_to admin_lots_url, notice: 'Lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_lot
      @admin_lot = Lot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_lot_params
      params.require(:admin_lot).permit(:yard_number, :yard_name, :sale_date, :sale_time, :item_no, :lot_number, :vehicle_type, :year, :make, :model_group, :model_detail, :body_style, :color, :damage_description, :secondary_damage, :sale_title_state, :sale_title_type, :has_keys, :lot_cond_code, :vin, :odometer, :odometer_brand, :est_retail_value, :engine, :drive, :transmission, :fuel_type, :cylinders, :runs_drives, :sale_status, :high_bid, :special_note, :city, :state, :zip, :country, :currency_code, :thumbnail, :cop_created_date, :grid_rows, :offer_eligible, :buy_now_price, :active_status)
    end

    def filtering_params(params)
    params.slice(:make, :color, :drive, :has_keys, :year, :state, :lot_number, :buy_now_price, :auction)
    end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController

	before_action :set_lot, only: [:show]

  def show
  	#render json: @lot
  	@bid = Bid.new
  	@watchlist = Watchlist.new
  end

  private

  def set_lot
      @lot = Lot.find(params[:id])
  end
end

app/helpers/admin/lots_helper.rb
module Admin::LotsHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/admin/lots/_form.html.erb
<%= form_for(admin_lot) do |f| %>
  <% if admin_lot.errors.any? %>
    <div class="alert alert-danger" role="alert" id="error_explanation">
      <% admin_lot.errors.full_messages.each do |message| %>
        <p class="mb-0"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <%= f.label :yard_number, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.number_field :yard_number, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :yard_name, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :yard_name, class: "form-control" %>    
        </div>
      </div>
      
    </div>
  </div>

  <div class="row">
    <%= f.label :sale_date, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :sale_date, class: "form-control", type: "date" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :sale_time, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :sale_time, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :item_no, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.number_field :item_no, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :lot_number, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.number_field :lot_number, class: "form-control" %>
        </div>  
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :vehicle_type, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :vehicle_type, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :year, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :year, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :make, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :make, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :model_group, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :model_group, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :model_detail, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :model_detail, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :body_style, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :body_style, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :color, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :color, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :damage_description, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :damage_description, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :secondary_damage, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :secondary_damage, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :sale_title_state, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :sale_title_state, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :sale_title_type, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :sale_title_type, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :has_keys, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :has_keys, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :lot_cond_code, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :lot_cond_code, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :vin, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :vin, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :odometer, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.number_field :odometer, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :odometer_brand, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :odometer_brand, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :est_retail_value, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.number_field :est_retail_value, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :engine, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :engine, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :drive, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :drive, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :transmission, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :transmission, class: "form-control" %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <%= f.label :fuel_type, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :fuel_type, class: "form-control" %>
      </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :cylinders, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.number_field :cylinders, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :runs_drives, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :runs_drives, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :sale_status, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :sale_status, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :high_bid, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.number_field :high_bid, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :special_note, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :special_note, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :city, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :city, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :state, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :state, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :zip, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :zip, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :country, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :country, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :currency_code, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :currency_code, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :thumbnail, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :thumbnail, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :cop_created_date, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :cop_created_date, class: "form-control", type: "date" %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <%= f.label :grid_rows, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :grid_rows, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :offer_eligible, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.text_field :offer_eligible, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :buy_now_price, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
      <%= f.number_field :buy_now_price, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="offset-sm-2 col-sm-10">
      <%= f.submit 'Submit', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/lots/edit.html.erb
<h1>Editing Admin Lot</h1>

<%= render 'form', admin_lot: @admin_lot %>

<%= link_to 'Show', @admin_lot %> |
<%= link_to 'Back', admin_lots_path %>

app/views/admin/lots/index.html.erb
 <!-- Basic Table -->
 <div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        Admin Lots
        <%= link_to 'New Admin Lot', new_admin_lot_path, :class=> "btn btn-small btn-primary pull-right" %>
        <ul class="header-dropdown m-r--5">
          <li class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">more_vert</i>
            </a>
            <ul class="dropdown-menu pull-right">
              <li><a href="javascript:void(0);">Action</a></li>
              <li><a href="javascript:void(0);">Another action</a></li>
              <li><a href="javascript:void(0);">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="body table-responsive">

        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Yard name</th>
              <th>Lot number</th>
              <th>Vehicle type</th>
              <th>Year</th>
              <th>Make</th>
              <th>Model group</th>
              <th>Model detail</th>
              <th>Body style</th>
              <th>Color</th>
              <th>Vin</th>
              <th>Odometer</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @admin_lots.each do |admin_lot| %>
            <tr>
              <td><%= admin_lot.yard_name %></td>
              <td><%= admin_lot.lot_number %></td>
              <td><%= admin_lot.vehicle_type %></td>
              <td><%= admin_lot.year %></td>
              <td><%= admin_lot.make %></td>
              <td><%= admin_lot.model_group %></td>
              <td><%= admin_lot.model_detail %></td>
              <td><%= admin_lot.body_style %></td>
              <td><%= admin_lot.color %></td>
              <td><%= admin_lot.vin %></td>
              <td><%= admin_lot.odometer %></td>
              <td><%= link_to 'Show', admin_lot %></td>
              <td><%= link_to 'Edit', edit_admin_lot_path(admin_lot) %></td>
              <td><%= link_to 'Destroy', admin_lot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
            <!-- #END# Basic Table -->

app/views/admin/lots/new.html.erb
 <!-- Basic Table -->
 <div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
				<h1>New Admin Lot</h1>
			</div>

<div class="body">
<%= render 'form', admin_lot: @admin_lot %>

<%= link_to 'Back', admin_lots_path %>
</div>
</div>

app/views/admin/lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Yard number:</strong>
  <%= @admin_lot.yard_number %>
</p>

<p>
  <strong>Yard name:</strong>
  <%= @admin_lot.yard_name %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @admin_lot.sale_date %>
</p>

<p>
  <strong>Sale time:</strong>
  <%= @admin_lot.sale_time %>
</p>

<p>
  <strong>Item no:</strong>
  <%= @admin_lot.item_no %>
</p>

<p>
  <strong>Lot number:</strong>
  <%= @admin_lot.lot_number %>
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @admin_lot.vehicle_type %>
</p>

<p>
  <strong>Year:</strong>
  <%= @admin_lot.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @admin_lot.make %>
</p>

<p>
  <strong>Model group:</strong>
  <%= @admin_lot.model_group %>
</p>

<p>
  <strong>Model detail:</strong>
  <%= @admin_lot.model_detail %>
</p>

<p>
  <strong>Body style:</strong>
  <%= @admin_lot.body_style %>
</p>

<p>
  <strong>Color:</strong>
  <%= @admin_lot.color %>
</p>

<p>
  <strong>Damage description:</strong>
  <%= @admin_lot.damage_description %>
</p>

<p>
  <strong>Secondary damage:</strong>
  <%= @admin_lot.secondary_damage %>
</p>

<p>
  <strong>Sale title state:</strong>
  <%= @admin_lot.sale_title_state %>
</p>

<p>
  <strong>Sale title type:</strong>
  <%= @admin_lot.sale_title_type %>
</p>

<p>
  <strong>Has keys:</strong>
  <%= @admin_lot.has_keys %>
</p>

<p>
  <strong>Lot cond code:</strong>
  <%= @admin_lot.lot_cond_code %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @admin_lot.vin %>
</p>

<p>
  <strong>Odometer:</strong>
  <%= @admin_lot.odometer %>
</p>

<p>
  <strong>Odometer brand:</strong>
  <%= @admin_lot.odometer_brand %>
</p>

<p>
  <strong>Est retail value:</strong>
  <%= @admin_lot.est_retail_value %>
</p>

<p>
  <strong>Engine:</strong>
  <%= @admin_lot.engine %>
</p>

<p>
  <strong>Drive:</strong>
  <%= @admin_lot.drive %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @admin_lot.transmission %>
</p>

<p>
  <strong>Fuel type:</strong>
  <%= @admin_lot.fuel_type %>
</p>

<p>
  <strong>Cylinders:</strong>
  <%= @admin_lot.cylinders %>
</p>

<p>
  <strong>Runs drives:</strong>
  <%= @admin_lot.runs_drives %>
</p>

<p>
  <strong>Sale status:</strong>
  <%= @admin_lot.sale_status %>
</p>

<p>
  <strong>High bid:</strong>
  <%= @admin_lot.high_bid %>
</p>

<p>
  <strong>Special note:</strong>
  <%= @admin_lot.special_note %>
</p>

<p>
  <strong>City:</strong>
  <%= @admin_lot.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @admin_lot.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @admin_lot.zip %>
</p>

<p>
  <strong>Country:</strong>
  <%= @admin_lot.country %>
</p>

<p>
  <strong>Currency code:</strong>
  <%= @admin_lot.currency_code %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @admin_lot.thumbnail %>
</p>

<p>
  <strong>Cop created date:</strong>
  <%= @admin_lot.cop_created_date %>
</p>

<p>
  <strong>Grid rows:</strong>
  <%= @admin_lot.grid_rows %>
</p>

<p>
  <strong>Offer eligible:</strong>
  <%= @admin_lot.offer_eligible %>
</p>

<p>
  <strong>Buy now price:</strong>
  <%= @admin_lot.buy_now_price %>
</p>

<%= link_to 'Edit', edit_admin_lot_path(@admin_lot) %> |
<%= link_to 'Back', admin_lots_path %>