config/routes.rb
Rails.application.routes.draw do


  get 'lots/show'
  get 'pages/home'
  get 'pages/csv'
  get 'pages/smarter'
  get 'search'   => 'search#index'
  get  'about'   => "pages#about"
  get  'faq'   => "pages#faq"
  get  'how_to_buy'   => "pages#how_to_buy"
  get  'why_mitsab'   => "pages#why_mitsab"
  get  'contact' => "pages#contact"
  post  'contact' => "pages#contact_email"
  get  'error' => "pages#error"

  
  devise_for :users

  resources :lots do
  	resources :bids
    resources :watchlists
  end

  resources :watchlists
  get "/my-bids" => "watchlists#bids"
  namespace :admin do
    get '', to: 'dashboard#index', as: '/' 
    get '/auction' => "dashboard#auction"
    resources :lots
    resources :users
    resources :reports
    resources :bulk_upload
    get 'csv/:id' => "bulk_upload#csv"
    get 'dashboard/upload' => "dashboard#upload_csv"
    get 'dashboard/resque' => "dashboard#resque"
    get 'bids/approve/:id' => "bids#approve"
    get 'bids/reject/:id' => "bids#reject"
    mount Resque::Server.new, :at => "/resque"
  end

  root "pages#home"
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # 

  validates :first_name, :last_name, :address_line1, :country, :state, :city, :phone, presence: true

  has_many :watchlists
  has_many :bids
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  def index
  	@users = User.paginate(:page => params[:page], :per_page => 100)
  end

  def new
  	@user = User.new
  end

  def edit
  end

  def create
  	@user = User.new(user_params)
  	# render json: @user
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'Successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'Lot was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'Lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_admin_user
      @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :company, :address_line1, :address_line2, :country, :state, :city, :zip, :phone , :email, :role)
  end

end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger" role="alert" id="error_explanation">
      <% user.errors.full_messages.each do |message| %>
        <p class="mb-0"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <%= f.label :first_name, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :last_name, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :email, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :company, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :company, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :address_line1, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :address_line1, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <%= f.label :country, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :country, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>  

  <div class="row">
    <%= f.label :country, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :country, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>  

  <div class="row">
    <%= f.label :state, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :state, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>  

  <div class="row">
    <%= f.label :city, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :city, class: "form-control" %>
        </div>
      </div>
    </div>
  </div> 

  <div class="row">
    <%= f.label :phone, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :phone, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>   

  <div class="row">
    <%= f.label :password, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :password, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>  

  <div class="row">
    <%= f.label :password_confirmation, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <%= f.text_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>  

  <div class="row">
    <%= f.label :role, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <div class="form-group">
        <div class="form-line">
          <select name="user[role]" id="" class="form-control show-tick ms">
            <option value="0">User</option>
            <option value="1">Manager</option>
            <option value="2">Staff</option>
            <option value="3">Admin</option>
          </select>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <%= f.submit t('.sign_up', :default => "Save"), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
 <div class="row clearfix">
 	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
 		<div class="card">
 			<div class="header">
 				<h4>Editing User</h4>
 			</div>
 			<div class="body">
 				<%= render 'form', user: @user %>
 			</div>
 		</div>
 	</div>
 </div>

app/views/admin/users/index.html.erb
 <!-- Basic Table -->
 <div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        All Users
        <%= link_to 'New User', new_admin_user_path, :class=> "btn btn-small btn-primary pull-right" %>
      </div>
      <div class="body table-responsive">

        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Id</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Role</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>
              <% if user.role == 0 %>
                <td>User</td>
              <% end %>
              <% if user.role == 1 %>
                <td>Manager</td>
              <% end %>
              <% if user.role == 2 %>
                <td>Staff<td>
              <% end %>
              <% if user.role == 3 %>
                <td>Admin</td>
              <% end %>
              <td><%= link_to 'Edit', edit_admin_user_url(user) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @users, class: "digg_pagination search-pagination", :previous_label => 'Previous', :next_label => 'Next' %>
      </div>
    </div>
  </div>
</div>

</div>
            <!-- #END# Basic Table -->

app/views/admin/users/new.html.erb
 <div class="row clearfix">
 	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
 		<div class="card">
 			<div class="header">
 				<h4>Add New User</h4>
 			</div>
 			<div class="body">
 				<%= render 'form', user: @user %>
 			</div>
 		</div>
 	</div>
 </div>